import Elementary

extension HTMLTrait.Attributes {
    protocol ariaInvalid {}
    protocol ariaDescribedby {}
}

extension HTMLTag.input: HTMLTrait.Attributes.ariaInvalid {}
extension HTMLTag.textarea: HTMLTrait.Attributes.ariaInvalid {}

extension HTMLAttribute where Tag: HTMLTrait.Attributes.ariaInvalid {
    static func ariaInvalid(_ invalid: Bool) -> Self {
        HTMLAttribute(name: "aria-invalid", value: invalid ? "true" : "false")
    }
}

extension HTMLTag.input: HTMLTrait.Attributes.ariaDescribedby {}
extension HTMLTag.textarea: HTMLTrait.Attributes.ariaDescribedby {}

extension HTMLAttribute where Tag: HTMLTrait.Attributes.ariaDescribedby {
    static func ariaDescribedby(_ id: String) -> Self {
        HTMLAttribute(name: "aria-describedby", value: id)
    }
}

// MARK: - valid

public extension HTMLVoidElement where Tag == HTMLTag.input {
    /// Usage:
    /// ```swift
    /// input().valid()
    /// input().valid(when: someCondition)
    /// ```
    ///
    /// - Parameters:
    ///   - condition: Whether to apply (default true).
    /// - Returns: Input element with aria-invalid if invalid.
    func valid(when condition: Bool = true) -> Self {
        attributes(.ariaInvalid(false), when: condition)
    }
    
    /// Usage:
    /// ```swift
    /// input().valid
    /// ```
    var valid: Self { attributes(.ariaInvalid(false)) }
    
    /// Usage:
    /// ```swift
    /// input().invalid()
    /// input().invalid(when: someCondition)
    /// ```
    ///
    /// - Parameters:
    ///   - condition: Whether to apply (default true).
    /// - Returns: Input element with aria-invalid if invalid.
    func invalid(when condition: Bool = true) -> Self {
        attributes(.ariaInvalid(true), when: condition)
    }
    
    /// Usage:
    /// ```swift
    /// input().invalid
    /// ```
    var invalid: Self { attributes(.ariaInvalid(true)) }
}

extension HTMLElement where Tag == HTMLTag.textarea {
    /// Usage:
    /// ```swift
    /// textarea { }.valid()
    /// textarea { }.valid(when: someCondition)
    /// ```
    ///
    /// - Parameters:
    ///   - condition: Whether to apply the attribute (default true).
    /// - Returns: Textarea with updated aria-invalid attribute.
    func valid(when condition: Bool = true) -> Self {
        attributes(.ariaInvalid(false), when: condition)
    }
    
    /// Usage:
    /// ```swift
    /// textarea { }.valid
    /// ```
    var valid: Self { attributes(.ariaInvalid(false)) }
    
    
    /// Usage:
    /// ```swift
    /// textarea { }.invalid()
    /// textarea { }.invalid(when: someCondition)
    /// ```
    ///
    /// - Parameters:
    ///   - condition: Whether to apply the attribute (default true).
    /// - Returns: Textarea with updated aria-invalid attribute.
    func invalid(when condition: Bool = true) -> Self {
        attributes(.ariaInvalid(true), when: condition)
    }
    
    /// Usage:
    /// ```swift
    /// textarea { }.invalid
    /// ```
    var invalid: Self { attributes(.ariaInvalid(true)) }
}


// MARK: - invalid
public extension HTMLTrait {
    protocol InvalidMessageTrait: HTML {
        associatedtype Input: HTML
        func invalid(ariaDescribedbyId: String, when condition: Bool) -> Input
    }
}

extension HTMLVoidElement: HTMLTrait.InvalidMessageTrait where Tag == HTMLTag.input {
    public typealias Input =  HTMLVoidElement<Tag>
    
    /// Generates an invalid message helper linking the input and message.
    ///
    /// Usage:
    /// ```swift
    /// input().invalid(message: "Invalid message")
    /// input().invalid(message: "Invalid message", when: someCondition)
    /// ```
    ///
    /// - Parameters:
    ///   - message: Validation error text.
    ///   - id: Optional ID for the error element; autogenerated if nil.
    ///   - condition: Whether to display the message (default true).
    /// - Returns: An InvalidMessage wrapper injecting accessibility attributes.
    public func invalid(message: String, id: String? = nil, when condition: Bool = true) -> InvalidMessage<Input> {
        let id = id ?? String(UInt64.random(in: 0...UInt64.max), radix: 16)
        return InvalidMessage(message: message, id: id, condition: condition, input: self)
    }
    
    @available(*, deprecated, message: "Use the invalid(message:when:) variant instead")
    public func invalid(ariaDescribedbyId: String, when condition: Bool) -> Input {
        self.attributes(.ariaInvalid(true), when: condition)
            .attributes(.ariaDescribedby(ariaDescribedbyId), when: condition)
    }
}

extension HTMLElement: HTMLTrait.InvalidMessageTrait where Tag == HTMLTag.textarea {
    public typealias Input = HTMLElement<HTMLTag.textarea, Content>
    
    /// Generates an invalid message helper linking the textarea and message.
    ///
    /// Usage:
    /// ```swift
    /// textarea { }.invalid(message: "Invalid message")
    /// textarea { }.invalid(message: "Invalid message", when: someCondition)
    /// ```
    ///
    /// - Parameters:
    ///   - message: Validation error text.
    ///   - id: Optional ID for the error element; autogenerated if nil.
    ///   - condition: Whether to display the message (default true).
    /// - Returns: An InvalidMessage wrapper injecting accessibility attributes.
    public func invalid(message: String, id: String? = nil, when condition: Bool = true) -> InvalidMessage<Input> {
        let id = id ?? String(UInt64.random(in: 0...UInt64.max), radix: 16)
        return InvalidMessage(message: message, id: id, condition: condition, input: self)
    }
    
    @available(*, deprecated, message: "Use the invalid(message:when:) variant instead")
    public func invalid(ariaDescribedbyId: String, when condition: Bool) -> Input {
        self.attributes(.ariaInvalid(true), when: condition)
            .attributes(.ariaDescribedby(ariaDescribedbyId), when: condition)
    }
}

/// A component that wraps an input and its validation message.
///
/// Usage:
/// ```swift
/// input().invalid(message: "Error text", when: validationFails)
/// textarea {}.invalid(message: "Error text", when: validationFails)
/// ```
public struct InvalidMessage<Input>: HTML where Input: HTMLTrait.InvalidMessageTrait {
    let message: String
    let id: String
    let condition: Bool
    let input: Input

    @HTMLBuilder public var body: some HTML {
        input.invalid(ariaDescribedbyId: id, when: condition)

        if condition {
            small(.id(id)) { message }
        }
    }
}

